package DB;
// Generated Jun 19, 2015 5:06:37 PM by Hibernate Tools 4.3.1



/**
 * MacroExecution generated by hbm2java
 */
public class MacroExecution  implements java.io.Serializable {


     private Integer idmacroExecution;
     private ScriptExecutions scriptExecutionsByScriptExecutionsIdscriptExecutions;
     private ScriptExecutions scriptExecutionsByScriptExecutionsIdscriptExecutions1;
     private Byte scriptOrder;

    public MacroExecution() {
    }

	
    public MacroExecution(ScriptExecutions scriptExecutionsByScriptExecutionsIdscriptExecutions, ScriptExecutions scriptExecutionsByScriptExecutionsIdscriptExecutions1) {
        this.scriptExecutionsByScriptExecutionsIdscriptExecutions = scriptExecutionsByScriptExecutionsIdscriptExecutions;
        this.scriptExecutionsByScriptExecutionsIdscriptExecutions1 = scriptExecutionsByScriptExecutionsIdscriptExecutions1;
    }
    public MacroExecution(ScriptExecutions scriptExecutionsByScriptExecutionsIdscriptExecutions, ScriptExecutions scriptExecutionsByScriptExecutionsIdscriptExecutions1, Byte scriptOrder) {
       this.scriptExecutionsByScriptExecutionsIdscriptExecutions = scriptExecutionsByScriptExecutionsIdscriptExecutions;
       this.scriptExecutionsByScriptExecutionsIdscriptExecutions1 = scriptExecutionsByScriptExecutionsIdscriptExecutions1;
       this.scriptOrder = scriptOrder;
    }
   
    public Integer getIdmacroExecution() {
        return this.idmacroExecution;
    }
    
    public void setIdmacroExecution(Integer idmacroExecution) {
        this.idmacroExecution = idmacroExecution;
    }
    public ScriptExecutions getScriptExecutionsByScriptExecutionsIdscriptExecutions() {
        return this.scriptExecutionsByScriptExecutionsIdscriptExecutions;
    }
    
    public void setScriptExecutionsByScriptExecutionsIdscriptExecutions(ScriptExecutions scriptExecutionsByScriptExecutionsIdscriptExecutions) {
        this.scriptExecutionsByScriptExecutionsIdscriptExecutions = scriptExecutionsByScriptExecutionsIdscriptExecutions;
    }
    public ScriptExecutions getScriptExecutionsByScriptExecutionsIdscriptExecutions1() {
        return this.scriptExecutionsByScriptExecutionsIdscriptExecutions1;
    }
    
    public void setScriptExecutionsByScriptExecutionsIdscriptExecutions1(ScriptExecutions scriptExecutionsByScriptExecutionsIdscriptExecutions1) {
        this.scriptExecutionsByScriptExecutionsIdscriptExecutions1 = scriptExecutionsByScriptExecutionsIdscriptExecutions1;
    }
    public Byte getScriptOrder() {
        return this.scriptOrder;
    }
    
    public void setScriptOrder(Byte scriptOrder) {
        this.scriptOrder = scriptOrder;
    }




}


