package DB;
// Generated Jun 24, 2015 5:05:36 PM by Hibernate Tools 4.3.1

/**
 * ParametersExecution generated by hbm2java
 */
public class ParametersExecution implements java.io.Serializable {

    private Integer idparameters;
    private Parameters parameters;
    private ScriptExecutions scriptExecutions;
    private String value;
    private Byte paramOrder;
    private String purpose;

    public ParametersExecution() {
    }

    public ParametersExecution(Parameters parameters, ScriptExecutions scriptExecutions) {
        this.parameters = parameters;
        this.scriptExecutions = scriptExecutions;
    }

    public ParametersExecution(Parameters parameters, ScriptExecutions scriptExecutions, String value, Byte paramOrder) {
        this.parameters = parameters;
        this.scriptExecutions = scriptExecutions;
        this.value = value;
        this.paramOrder = paramOrder;
    }

    public Integer getIdparameters() {
        return this.idparameters;
    }

    public void setIdparameters(Integer idparameters) {
        this.idparameters = idparameters;
    }

    public Parameters getParameters() {
        return this.parameters;
    }

    public void setParameters(Parameters parameters) {
        this.parameters = parameters;
    }

    public ScriptExecutions getScriptExecutions() {
        return this.scriptExecutions;
    }

    public void setScriptExecutions(ScriptExecutions scriptExecutions) {
        this.scriptExecutions = scriptExecutions;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public Byte getParamOrder() {
        return this.paramOrder;
    }

    public void setParamOrder(Byte paramOrder) {
        this.paramOrder = paramOrder;
            }
    
    public void setPurpose(String purpose){
        this.purpose=purpose;
    }

    public String getPurpose(){
        return this.purpose;
    }

}
