package DB;
// Generated Jun 19, 2015 5:06:37 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TestStep generated by hbm2java
 */
public class TestStep implements java.io.Serializable,Comparable<TestStep> {

    private Integer idtestStep;
    private TestCase testCase;
    private String writer;
    private String humanStimuli;
    private String humanCheck;
    private String creationDate;
    private String editionDate;
    private Byte stepOrder;
    private Boolean blockingStep;
    private Boolean stepCondition;
    private Set stepExecutionses = new HashSet(0);
    private Set requirements = new HashSet(0);
    private Set testStepHasScripts = new HashSet(0);

    public TestStep() {
    }

    public TestStep(TestCase testCase, String writer, String humanStimuli, String humanCheck, String creationDate, String editionDate, Byte stepOrder, Boolean blockingStep, Boolean stepCondition, Set stepExecutionses, Set requirements, Set testStepHasScripts) {
        this.testCase = testCase;
        this.writer = writer;
        this.humanStimuli = humanStimuli;
        this.humanCheck = humanCheck;
        this.creationDate = creationDate;
        this.editionDate = editionDate;
        this.stepOrder = stepOrder;
        this.blockingStep = blockingStep;
        this.stepCondition = stepCondition;
        this.stepExecutionses = stepExecutionses;
        this.requirements = requirements;
        this.testStepHasScripts = testStepHasScripts;
    }

    public TestStep(TestStep step) {
        this.testCase = step.getTestCase();
        this.writer = step.getWriter();
        this.humanStimuli = step.getHumanStimuli();
        this.humanCheck = step.getHumanCheck();
        this.creationDate = step.getCreationDate();
        this.editionDate = step.getEditionDate();
        this.stepOrder = step.getStepOrder();
        this.blockingStep = step.getBlockingStep();
        this.stepCondition = step.getStepCondition();
        this.requirements = step.getRequirements();
        this.testStepHasScripts = step.getTestStepHasScripts();
    }

    public Integer getIdtestStep() {
        return this.idtestStep;
    }

    public void setIdtestStep(Integer idtestStep) {
        this.idtestStep = idtestStep;
    }

    public TestCase getTestCase() {
        return this.testCase;
    }

    public void setTestCase(TestCase testCase) {
        this.testCase = testCase;
    }

    public String getWriter() {
        return this.writer;
    }

    public void setWriter(String writer) {
        this.writer = writer;
    }

    public String getHumanStimuli() {
        return this.humanStimuli;
    }

    public void setHumanStimuli(String humanStimuli) {
        this.humanStimuli = humanStimuli;
    }

    public String getHumanCheck() {
        return this.humanCheck;
    }

    public void setHumanCheck(String humanCheck) {
        this.humanCheck = humanCheck;
    }

    public String getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(String creationDate) {
        this.creationDate = creationDate;
    }

    public String getEditionDate() {
        return this.editionDate;
    }

    public void setEditionDate(String editionDate) {
        this.editionDate = editionDate;
    }

    public Byte getStepOrder() {
        return this.stepOrder;
    }

    public void setStepOrder(Byte stepOrder) {
        this.stepOrder = stepOrder;
    }

    public Boolean getBlockingStep() {
        return this.blockingStep;
    }

    public void setBlockingStep(Boolean blockingStep) {
        this.blockingStep = blockingStep;
    }

    public Boolean getStepCondition() {
        return this.stepCondition;
    }

    public void setStepCondition(Boolean stepCondition) {
        this.stepCondition = stepCondition;
    }

    public Set getStepExecutionses() {
        return this.stepExecutionses;
    }

    public void setStepExecutionses(Set stepExecutionses) {
        this.stepExecutionses = stepExecutionses;
    }

    public Set getRequirements() {
        return this.requirements;
    }

    public void setRequirements(Set requirements) {
        this.requirements = requirements;
    }

    public Set getTestStepHasScripts() {
        return this.testStepHasScripts;
    }

    public void setTestStepHasScripts(Set testStepHasScripts) {
        this.testStepHasScripts = testStepHasScripts;
    }

    public void addTestStephasScript(TestStepHasScript testStepHasScript) {
        testStepHasScript.setTestStep(this);
        this.testStepHasScripts.add(testStepHasScript);
    }

    @Override
    public int compareTo(TestStep o) {
        return Integer.compare(this.getStepOrder(), o.getStepOrder());
    }

}
