package DB;
// Generated Jun 19, 2015 5:06:37 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TestCase generated by hbm2java
 */
public class TestCase implements java.io.Serializable {

    private Integer idtestCase;
    private String testCaseTitle;
    private String writter;
    private Byte caseInternalVersion;
    private String creationDate;
    private String editionDate;
    private String testCaseIdentification;
    private String testCaseVersion;
    private String project;
    private String typeOfTest;
    private String categoryOfTest;
    private String location;
    private String environment;
    private String testObjective;
    private Byte totalSteps;
    private String writterEmail;
    private String writingStatus;
    private String testMethodIadt;
    private Byte blocking;
    private String internalComments;
    private String testCaseSource;
    private Set testSteps = new HashSet(0);
    private Set testCampaignTestCases = new HashSet(0);
    private Set caseExecutionses = new HashSet(0);
    private SimpleStringProperty simpleStringConfigured;

    public TestCase() {
    }

    public TestCase(String testCaseTitle, String writter, Byte caseInternalVersion, String creationDate, String editionDate, String testCaseIdentification, String testCaseVersion, String project, String typeOfTest, String categoryOfTest, String location, String environment, String testObjective, Byte totalSteps, String writterEmail, String writingStatus, String testMethodIadt, Byte blocking, String internalComments, String testCaseSource, Set testSteps, Set testCampaignTestCases, Set caseExecutionses) {
        this.testCaseTitle = testCaseTitle;
        this.writter = writter;
        this.caseInternalVersion = caseInternalVersion;
        this.creationDate = creationDate;
        this.editionDate = editionDate;
        this.testCaseIdentification = testCaseIdentification;
        this.testCaseVersion = testCaseVersion;
        this.project = project;
        this.typeOfTest = typeOfTest;
        this.categoryOfTest = categoryOfTest;
        this.location = location;
        this.environment = environment;
        this.testObjective = testObjective;
        this.totalSteps = totalSteps;
        this.writterEmail = writterEmail;
        this.writingStatus = writingStatus;
        this.testMethodIadt = testMethodIadt;
        this.blocking = blocking;
        this.internalComments = internalComments;
        this.testCaseSource = testCaseSource;
        this.testSteps = testSteps;
        this.testCampaignTestCases = testCampaignTestCases;
        this.caseExecutionses = caseExecutionses;
    }

    public TestCase(TestCase testCase) {
        this.testCaseTitle = testCase.getTestCaseTitle();
        this.writter = testCase.getWritter();
        this.caseInternalVersion = testCase.getCaseInternalVersion();
        this.creationDate = testCase.getCreationDate();
        this.editionDate = testCase.getEditionDate();
        this.testCaseIdentification = testCase.getTestCaseIdentification();
        this.testCaseVersion = testCase.getTestCaseVersion();
        this.project = testCase.getProject();
        this.typeOfTest = testCase.getTypeOfTest();
        this.categoryOfTest = testCase.getCategoryOfTest();
        this.location = testCase.getLocation();
        this.environment = testCase.getEnvironment();
        this.testObjective = testCase.getTestObjective();
        this.totalSteps = testCase.getTotalSteps();
        this.writterEmail = testCase.getWritterEmail();
        this.writingStatus = testCase.getWritingStatus();
        this.testMethodIadt = testCase.getTestMethodIadt();
        this.blocking = testCase.getBlocking();
        this.internalComments = testCase.getInternalComments();
        this.testCaseSource = testCase.getTestCaseSource();
        this.testSteps = testCase.getTestSteps();
        this.testCampaignTestCases = testCase.getTestCampaignTestCases();
        this.caseExecutionses = testCase.getCaseExecutionses();
    }

    public TestCase(String testCaseTitle, String writter, Byte caseInternalVersion, String creationDate, String editionDate, String testCaseIdentification, String testCaseVersion, String project, String typeOfTest, String categoryOfTest, String location, String environment, String testObjective, Byte totalSteps, String writterEmail, String writingStatus, String testMethodIadt, Byte blocking, String internalComments, String testCaseSource) {
        this.testCaseTitle = testCaseTitle;
        this.writter = writter;
        this.caseInternalVersion = caseInternalVersion;
        this.creationDate = creationDate;
        this.editionDate = editionDate;
        this.testCaseIdentification = testCaseIdentification;
        this.testCaseVersion = testCaseVersion;
        this.project = project;
        this.typeOfTest = typeOfTest;
        this.categoryOfTest = categoryOfTest;
        this.location = location;
        this.environment = environment;
        this.testObjective = testObjective;
        this.totalSteps = totalSteps;
        this.writterEmail = writterEmail;
        this.writingStatus = writingStatus;
        this.testMethodIadt = testMethodIadt;
        this.blocking = blocking;
        this.internalComments = internalComments;
        this.testCaseSource = testCaseSource;
    }

//    public TestCase(String testCaseTitle, String writter, Byte caseInternalVersion, Date creationDate, Date editionDate, String testCaseIdentification, String testCaseVersion, String project, String typeOfTest, String categoryOfTest, String location, String environment, String testObjective, Byte totalSteps, String writterEmail, String writingStatus, String testMethodIadt, Byte blocking, String internalComments, String testCaseSource, Set testSteps, Set testCampaignTestCases, Set caseExecutionses) {
//       this.testCaseTitle = testCaseTitle;
//       this.writter = writter;
//       this.caseInternalVersion = caseInternalVersion;
//       this.creationDate = creationDate;
//       this.editionDate = editionDate;
//       this.testCaseIdentification = testCaseIdentification;
//       this.testCaseVersion = testCaseVersion;
//       this.project = project;
//       this.typeOfTest = typeOfTest;
//       this.categoryOfTest = categoryOfTest;
//       this.location = location;
//       this.environment = environment;
//       this.testObjective = testObjective;
//       this.totalSteps = totalSteps;
//       this.writterEmail = writterEmail;
//       this.writingStatus = writingStatus;
//       this.testMethodIadt = testMethodIadt;
//       this.blocking = blocking;
//       this.internalComments = internalComments;
//       this.testCaseSource = testCaseSource;
//       this.testSteps = testSteps;
//       this.testCampaignTestCases = testCampaignTestCases;
//       this.caseExecutionses = caseExecutionses;
//    }
    public Integer getIdtestCase() {
        return this.idtestCase;
    }

    public void setIdtestCase(Integer idtestCase) {
        this.idtestCase = idtestCase;
    }

    public String getTestCaseTitle() {
        return this.testCaseTitle;
    }

    public void setTestCaseTitle(String testCaseTitle) {
        this.testCaseTitle = testCaseTitle;
    }

    public String getWritter() {
        return this.writter;
    }

    public void setWritter(String writter) {
        this.writter = writter;
    }

    public Byte getCaseInternalVersion() {
        return this.caseInternalVersion;
    }

    public void setCaseInternalVersion(Byte caseInternalVersion) {
        this.caseInternalVersion = caseInternalVersion;
    }

    public String getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(String creationDate) {
        this.creationDate = creationDate;
    }

    public String getEditionDate() {
        return this.editionDate;
    }

    public void setEditionDate(String editionDate) {
        this.editionDate = editionDate;
    }

    public String getTestCaseIdentification() {
        return this.testCaseIdentification;
    }

    public void setTestCaseIdentification(String testCaseIdentification) {
        this.testCaseIdentification = testCaseIdentification;
    }

    public String getTestCaseVersion() {
        return this.testCaseVersion;
    }

    public void setTestCaseVersion(String testCaseVersion) {
        this.testCaseVersion = testCaseVersion;
    }

    public String getProject() {
        return this.project;
    }

    public void setProject(String project) {
        this.project = project;
    }

    public String getTypeOfTest() {
        return this.typeOfTest;
    }

    public void setTypeOfTest(String typeOfTest) {
        this.typeOfTest = typeOfTest;
    }

    public String getCategoryOfTest() {
        return this.categoryOfTest;
    }

    public void setCategoryOfTest(String categoryOfTest) {
        this.categoryOfTest = categoryOfTest;
    }

    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getEnvironment() {
        return this.environment;
    }

    public void setEnvironment(String environment) {
        this.environment = environment;
    }

    public String getTestObjective() {
        return this.testObjective;
    }

    public void setTestObjective(String testObjective) {
        this.testObjective = testObjective;
    }

    public Byte getTotalSteps() {
        return this.totalSteps;
    }

    public void setTotalSteps(Byte totalSteps) {
        this.totalSteps = totalSteps;
    }

    public String getWritterEmail() {
        return this.writterEmail;
    }

    public void setWritterEmail(String writterEmail) {
        this.writterEmail = writterEmail;
    }

    public String getWritingStatus() {
        return this.writingStatus;
    }

    public void setWritingStatus(String writingStatus) {
        this.writingStatus = writingStatus;
    }

    public String getTestMethodIadt() {
        return this.testMethodIadt;
    }

    public void setTestMethodIadt(String testMethodIadt) {
        this.testMethodIadt = testMethodIadt;
    }

    public Byte getBlocking() {
        return this.blocking;
    }

    public void setBlocking(Byte blocking) {
        this.blocking = blocking;
    }

    public String getInternalComments() {
        return this.internalComments;
    }

    public void setInternalComments(String internalComments) {
        this.internalComments = internalComments;
    }

    public String getTestCaseSource() {
        return this.testCaseSource;
    }

    public void setTestCaseSource(String testCaseSource) {
        this.testCaseSource = testCaseSource;
    }

    public Set getTestSteps() {
        return this.testSteps;
    }

    public void setTestSteps(Set testSteps) {
        this.testSteps = testSteps;
    }

    public Set getTestCampaignTestCases() {
        return this.testCampaignTestCases;
    }

    public void setTestCampaignTestCases(Set testCampaignTestCases) {
        this.testCampaignTestCases = testCampaignTestCases;
    }

    public Set getCaseExecutionses() {
        return this.caseExecutionses;
    }

    public void setCaseExecutionses(Set caseExecutionses) {
        this.caseExecutionses = caseExecutionses;
    }

    public void setConfigured(String configured) {
        simpleStringConfiguredProperty().set(configured);
    }

    public String getSimpleStringConfiguredProperty() {
        return this.simpleStringConfigured.get();
    }

    public StringProperty simpleStringConfiguredProperty() {
        if (simpleStringConfigured == null) {
            simpleStringConfigured = new SimpleStringProperty(this, "NConfigured");
        }
        return simpleStringConfigured;
    }

    public void addStep(TestStep testStep) {
        testStep.setTestCase(this);
        this.testSteps.add(testStep);
    }
}
