package DB;
// Generated Jul 7, 2015 10:16:27 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Macro generated by hbm2java
 */
public class Macro implements java.io.Serializable {

    private Integer idmacro;
    private Script scriptByScriptIdScript;
    private Script scriptByScriptIdScript1;
    private Byte scriptOrder;
    private Set paramScriptMacros = new HashSet(0);

    public Macro() {
    }

    public Macro(Script scriptByScriptIdScript, Script scriptByScriptIdScript1) {
        this.scriptByScriptIdScript = scriptByScriptIdScript;
        this.scriptByScriptIdScript1 = scriptByScriptIdScript1;
    }

    public Macro(Script scriptByScriptIdScript, Script scriptByScriptIdScript1, Byte scriptOrder, Set paramScriptMacros) {
        this.scriptByScriptIdScript = scriptByScriptIdScript;
        this.scriptByScriptIdScript1 = scriptByScriptIdScript1;
        this.scriptOrder = scriptOrder;
        this.paramScriptMacros = paramScriptMacros;
    }

    public Integer getIdmacro() {
        return this.idmacro;
    }

    public void setIdmacro(Integer idmacro) {
        this.idmacro = idmacro;
    }

    public Script getScriptByScriptIdScript() {
        return this.scriptByScriptIdScript;
    }

    public void setScriptByScriptIdScript(Script scriptByScriptIdScript) {
        this.scriptByScriptIdScript = scriptByScriptIdScript;
    }

    public Script getScriptByScriptIdScript1() {
        return this.scriptByScriptIdScript1;
    }

    public void setScriptByScriptIdScript1(Script scriptByScriptIdScript1) {
        this.scriptByScriptIdScript1 = scriptByScriptIdScript1;
    }

    public Byte getScriptOrder() {
        return this.scriptOrder;
    }

    public void setScriptOrder(Byte scriptOrder) {
        this.scriptOrder = scriptOrder;
    }

    public Set getParamScriptMacros() {
        return this.paramScriptMacros;
    }

    public void setParamScriptMacros(Set paramScriptMacros) {
        this.paramScriptMacros = paramScriptMacros;
    }

    public void addParamScriptMacro(ParamScriptMacro paramScriptMacro) {
        paramScriptMacro.setMacro(this);
        this.paramScriptMacros.add(paramScriptMacro);
    }

}
