package DB;
// Generated Jun 22, 2015 4:48:57 PM by Hibernate Tools 4.3.1

/**
 * ScriptHasBeenConfigured generated by hbm2java
 */
public class ScriptHasBeenConfigured implements java.io.Serializable,Comparable<ScriptHasBeenConfigured> {

    private Integer idscriptHasBeenConfigured;
    private Parameters parameters;
    private TestStepHasScript testStepHasScript;
    private Byte isConfigured = 0;
    private String value = "";
    private String valuePath = "";
    private byte paramOrder;

    public ScriptHasBeenConfigured() {
    }

    public ScriptHasBeenConfigured(TestStepHasScript testStepHasScript, byte paramOrder) {
        this.testStepHasScript = testStepHasScript;
        this.paramOrder = paramOrder;
    }

    public ScriptHasBeenConfigured(TestStepHasScript testStepHasScript, byte paramOrder, Byte isConfigured, String value, String valuePath) {
        this.testStepHasScript = testStepHasScript;
        this.paramOrder = paramOrder;
        this.isConfigured = isConfigured;
        this.value = value;
        this.valuePath = valuePath;
    }
    
    public ScriptHasBeenConfigured(ScriptHasBeenConfigured shbc,TestStepHasScript tshs){
        this.parameters=shbc.getParameters();
        this.testStepHasScript=tshs;
        this.isConfigured=shbc.getIsConfigured();
        this.value=shbc.getValue();
        this.valuePath=shbc.getValuePath();
        this.paramOrder=shbc.getParamOrder();  
    }

    public Integer getIdscriptHasBeenConfigured() {
        return this.idscriptHasBeenConfigured;
    }

    public void setIdscriptHasBeenConfigured(Integer idscriptHasBeenConfigured) {
        this.idscriptHasBeenConfigured = idscriptHasBeenConfigured;
    }

    public TestStepHasScript getTestStepHasScript() {
        return this.testStepHasScript;
    }

    public void setTestStepHasScript(TestStepHasScript testStepHasScript) {
        this.testStepHasScript = testStepHasScript;
    }

    public byte getParamOrder() {
        return this.paramOrder;
    }

    public void setParamOrder(byte paramOrder) {
        this.paramOrder = paramOrder;
    }

    public Byte getIsConfigured() {
        return this.isConfigured;
    }

    public void setIsConfigured(Byte isConfigured) {
        this.isConfigured = isConfigured;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public String getValuePath() {
        return this.valuePath;
    }

    public void setValuePath(String valuePath) {
        this.valuePath = valuePath;
    }

    public Parameters getParameters() {
        return this.parameters;
    }

    public void setParameters(Parameters parameters) {
        this.parameters = parameters;

    }

    @Override
    public int compareTo(ScriptHasBeenConfigured o) {
        return Integer.compare(this.getParamOrder(), o.getParamOrder());
    }
}
