package DB;
// Generated Jun 19, 2015 5:06:37 PM by Hibernate Tools 4.3.1



/**
 * ScriptExecutionResult generated by hbm2java
 */
public class ScriptExecutionResult  implements java.io.Serializable {


     private ScriptExecutionResultId id;
     private ScriptExecutions scriptExecutions;
     private String result;
     private String comment;

    public ScriptExecutionResult() {
    }

	
    public ScriptExecutionResult(ScriptExecutionResultId id, ScriptExecutions scriptExecutions, String result) {
        this.id = id;
        this.scriptExecutions = scriptExecutions;
        this.result = result;
    }
    public ScriptExecutionResult(ScriptExecutionResultId id, ScriptExecutions scriptExecutions, String result, String comment) {
       this.id = id;
       this.scriptExecutions = scriptExecutions;
       this.result = result;
       this.comment = comment;
    }
   
    public ScriptExecutionResultId getId() {
        return this.id;
    }
    
    public void setId(ScriptExecutionResultId id) {
        this.id = id;
    }
    public ScriptExecutions getScriptExecutions() {
        return this.scriptExecutions;
    }
    
    public void setScriptExecutions(ScriptExecutions scriptExecutions) {
        this.scriptExecutions = scriptExecutions;
    }
    public String getResult() {
        return this.result;
    }
    
    public void setResult(String result) {
        this.result = result;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


