package DB;
// Generated Jun 19, 2015 5:06:37 PM by Hibernate Tools 4.3.1



/**
 * CaseExecutionsResultId generated by hbm2java
 */
public class CaseExecutionsResultId  implements java.io.Serializable {


     private int caseExecutionsIdcaseExecutions;
     private byte iterationNumber;

    public CaseExecutionsResultId() {
    }

    public CaseExecutionsResultId(int caseExecutionsIdcaseExecutions, byte iterationNumber) {
       this.caseExecutionsIdcaseExecutions = caseExecutionsIdcaseExecutions;
       this.iterationNumber = iterationNumber;
    }
   
    public int getCaseExecutionsIdcaseExecutions() {
        return this.caseExecutionsIdcaseExecutions;
    }
    
    public void setCaseExecutionsIdcaseExecutions(int caseExecutionsIdcaseExecutions) {
        this.caseExecutionsIdcaseExecutions = caseExecutionsIdcaseExecutions;
    }
    public byte getIterationNumber() {
        return this.iterationNumber;
    }
    
    public void setIterationNumber(byte iterationNumber) {
        this.iterationNumber = iterationNumber;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CaseExecutionsResultId) ) return false;
		 CaseExecutionsResultId castOther = ( CaseExecutionsResultId ) other; 
         
		 return (this.getCaseExecutionsIdcaseExecutions()==castOther.getCaseExecutionsIdcaseExecutions())
 && (this.getIterationNumber()==castOther.getIterationNumber());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCaseExecutionsIdcaseExecutions();
         result = 37 * result + this.getIterationNumber();
         return result;
   }   


}


