package DB;
// Generated Jul 7, 2015 10:16:27 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Parameters generated by hbm2java
 */
public class Parameters implements java.io.Serializable {

    private Integer idparameters;
    private String name;
    private String parameterType;
    private String description;
    private Set scriptHasBeenConfigureds = new HashSet(0);
    private Set parametersExecutions = new HashSet(0);
    private Set scriptHasParameterses = new HashSet(0);

    public Parameters() {
    }

    public Parameters(Parameters param) {
        this.idparameters = param.getIdparameters();
        this.name = param.getName();
        this.parameterType = param.getParameterType();
        this.description = param.getDescription();
    }

    public Parameters(String name, String parameterType, String description, Set scriptHasBeenConfigureds, Set parametersExecutions, Set scriptHasParameterses) {
        this.name = name;
        this.parameterType = parameterType;
        this.description = description;
        this.scriptHasBeenConfigureds = scriptHasBeenConfigureds;
        this.parametersExecutions = parametersExecutions;
        this.scriptHasParameterses = scriptHasParameterses;
    }

    public Integer getIdparameters() {
        return this.idparameters;
    }

    public void setIdparameters(Integer idparameters) {
        this.idparameters = idparameters;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getParameterType() {
        return this.parameterType;
    }

    public void setParameterType(String parameterType) {
        this.parameterType = parameterType;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Set getScriptHasBeenConfigureds() {
        return this.scriptHasBeenConfigureds;
    }

    public void setScriptHasBeenConfigureds(Set scriptHasBeenConfigureds) {
        this.scriptHasBeenConfigureds = scriptHasBeenConfigureds;
    }

    public Set getParametersExecutions() {
        return this.parametersExecutions;
    }

    public void setParametersExecutions(Set parametersExecutions) {
        this.parametersExecutions = parametersExecutions;
    }

    public Set getScriptHasParameterses() {
        return this.scriptHasParameterses;
    }

    public void setScriptHasParameterses(Set scriptHasParameterses) {
        this.scriptHasParameterses = scriptHasParameterses;
    }

}
