package DB;
// Generated Jul 7, 2015 4:40:41 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ScriptHasParameters generated by hbm2java
 */
public class ScriptHasParameters  implements java.io.Serializable {


     private Integer idscriptHasParameters;
     private Parameters parameters;
     private Script script;
     private byte paramOrder;
     private Set paramScriptMacros = new HashSet(0);

    public ScriptHasParameters() {
    }

    public ScriptHasParameters(ScriptHasParameters schp){
        this.parameters=new Parameters(schp.getParameters());
    }
    
    public ScriptHasParameters(Parameters parameters, Script script, byte paramOrder) {
        this.parameters = parameters;
        this.script = script;
        this.paramOrder = paramOrder;
    }
    public ScriptHasParameters(Parameters parameters, Script script, byte paramOrder, Set paramScriptMacros) {
       this.parameters = parameters;
       this.script = script;
       this.paramOrder = paramOrder;
       this.paramScriptMacros = paramScriptMacros;
    }
   
    public Integer getIdscriptHasParameters() {
        return this.idscriptHasParameters;
    }
    
    public void setIdscriptHasParameters(Integer idscriptHasParameters) {
        this.idscriptHasParameters = idscriptHasParameters;
    }
    public Parameters getParameters() {
        return this.parameters;
    }
    
    public void setParameters(Parameters parameters) {
        this.parameters = parameters;
    }
    public Script getScript() {
        return this.script;
    }
    
    public void setScript(Script script) {
        this.script = script;
    }
    public byte getParamOrder() {
        return this.paramOrder;
    }
    
    public void setParamOrder(byte paramOrder) {
        this.paramOrder = paramOrder;
    }
    public Set getParamScriptMacros() {
        return this.paramScriptMacros;
    }
    
    public void setParamScriptMacros(Set paramScriptMacros) {
        this.paramScriptMacros = paramScriptMacros;
    }




}


