package DB;
// Generated Jun 19, 2015 5:06:37 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * ScriptExecutions generated by hbm2java
 */
public class ScriptExecutions implements java.io.Serializable {

    private Integer idscriptExecutions;
    private Script script;
    private StepExecutions stepExecutions;
    private Byte scriptOrder;
    private Byte isStimuli;
    private Set macroExecutionsForScriptExecutionsIdscriptExecutions = new HashSet(0);
    private Set macroExecutionsForScriptExecutionsIdscriptExecutions1 = new HashSet(0);
    private Set parametersExecutions = new HashSet(0);
    private Set scriptExecutionResults = new HashSet(0);
    private String result;
    private String comment;


    public ScriptExecutions() {
    }

    public ScriptExecutions(Script script, StepExecutions stepExecutions) {
        this.script = script;
        this.stepExecutions = stepExecutions;
    }

    public ScriptExecutions(Script script, StepExecutions stepExecutions, Byte scriptOrder, Byte isStimuli) {
        this.script = script;
        this.stepExecutions = stepExecutions;
        this.scriptOrder = scriptOrder;
        this.isStimuli = isStimuli;
    }

    public ScriptExecutions(Script script, StepExecutions stepExecutions, Byte scriptOrder, Byte isStimuli, Set macroExecutionsForScriptExecutionsIdscriptExecutions, Set macroExecutionsForScriptExecutionsIdscriptExecutions1, Set parametersExecutions, Set scriptExecutionResults) {
        this.script = script;
        this.stepExecutions = stepExecutions;
        this.scriptOrder = scriptOrder;
        this.isStimuli = isStimuli;
        this.macroExecutionsForScriptExecutionsIdscriptExecutions = macroExecutionsForScriptExecutionsIdscriptExecutions;
        this.macroExecutionsForScriptExecutionsIdscriptExecutions1 = macroExecutionsForScriptExecutionsIdscriptExecutions1;
        this.parametersExecutions = parametersExecutions;
        this.scriptExecutionResults = scriptExecutionResults;
    }

    public Integer getIdscriptExecutions() {
        return this.idscriptExecutions;
    }

    public void setIdscriptExecutions(Integer idscriptExecutions) {
        this.idscriptExecutions = idscriptExecutions;
    }

    public Script getScript() {
        return this.script;
    }

    public void setScript(Script script) {
        this.script = script;
    }

    public StepExecutions getStepExecutions() {
        return this.stepExecutions;
    }

    public void setStepExecutions(StepExecutions stepExecutions) {
        this.stepExecutions = stepExecutions;
    }

    public Byte getScriptOrder() {
        return this.scriptOrder;
    }

    public void setScriptOrder(Byte scriptOrder) {
        this.scriptOrder = scriptOrder;
    }

    public Byte getIsStimuli() {
        return this.isStimuli;
    }

    public void setIsStimuli(Byte isStimuli) {
        this.isStimuli = isStimuli;
    }

    public Set getMacroExecutionsForScriptExecutionsIdscriptExecutions() {
        return this.macroExecutionsForScriptExecutionsIdscriptExecutions;
    }

    public void setMacroExecutionsForScriptExecutionsIdscriptExecutions(Set macroExecutionsForScriptExecutionsIdscriptExecutions) {
        this.macroExecutionsForScriptExecutionsIdscriptExecutions = macroExecutionsForScriptExecutionsIdscriptExecutions;
    }

    public Set getMacroExecutionsForScriptExecutionsIdscriptExecutions1() {
        return this.macroExecutionsForScriptExecutionsIdscriptExecutions1;
    }

    public void setMacroExecutionsForScriptExecutionsIdscriptExecutions1(Set macroExecutionsForScriptExecutionsIdscriptExecutions1) {
        this.macroExecutionsForScriptExecutionsIdscriptExecutions1 = macroExecutionsForScriptExecutionsIdscriptExecutions1;
    }

    public Set getParametersExecutions() {
        return this.parametersExecutions;
    }

    public void setParametersExecutions(Set parametersExecutions) {
        this.parametersExecutions = parametersExecutions;
    }

    public Set getScriptExecutionResults() {
        return this.scriptExecutionResults;
    }

    public void setScriptExecutionResults(Set scriptExecutionResults) {
        this.scriptExecutionResults = scriptExecutionResults;
    }

    public void setScriptExecutionResult(String result) {
        this.result = result;
    }

    public String getScriptExecutionResult() {
        return this.result;
    }

    public void setScriptExecutionComment(String comment) {
        this.comment = comment;
    }

    public String getScriptExecutionComment() {
        return this.comment;
    }

}
