package DB;
// Generated Jun 19, 2015 5:06:37 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * ScriptExecutions generated by hbm2java
 */
public class ScriptExecutions implements java.io.Serializable {

    private Integer idscriptExecutions;
    private Script script;
    private StepExecutions stepExecutions;
    private Byte scriptOrder;
    private Byte isStimuli;
    private Set macroExecutionsForScriptExecutionsIdscriptExecutions = new HashSet(0);
    private Set macroExecutionsForScriptExecutionsIdscriptExecutions1 = new HashSet(0);
    private Set parametersExecutions = new HashSet(0);
    private Set scriptExecutionResults = new HashSet(0);
    private String result;
    private String comment;

    /**
     *
     */
    public ScriptExecutions() {
    }

    /**
     *
     * @param script
     * @param stepExecutions
     */
    public ScriptExecutions(Script script, StepExecutions stepExecutions) {
        this.script = script;
        this.stepExecutions = stepExecutions;
    }

    /**
     *
     * @param script
     * @param stepExecutions
     * @param scriptOrder
     * @param isStimuli
     */
    public ScriptExecutions(Script script, StepExecutions stepExecutions, Byte scriptOrder, Byte isStimuli) {
        this.script = script;
        this.stepExecutions = stepExecutions;
        this.scriptOrder = scriptOrder;
        this.isStimuli = isStimuli;
    }

    /**
     *
     * @param script
     * @param stepExecutions
     * @param scriptOrder
     * @param isStimuli
     * @param macroExecutionsForScriptExecutionsIdscriptExecutions
     * @param macroExecutionsForScriptExecutionsIdscriptExecutions1
     * @param parametersExecutions
     * @param scriptExecutionResults
     */
    public ScriptExecutions(Script script, StepExecutions stepExecutions, Byte scriptOrder, Byte isStimuli, Set macroExecutionsForScriptExecutionsIdscriptExecutions, Set macroExecutionsForScriptExecutionsIdscriptExecutions1, Set parametersExecutions, Set scriptExecutionResults) {
        this.script = script;
        this.stepExecutions = stepExecutions;
        this.scriptOrder = scriptOrder;
        this.isStimuli = isStimuli;
        this.macroExecutionsForScriptExecutionsIdscriptExecutions = macroExecutionsForScriptExecutionsIdscriptExecutions;
        this.macroExecutionsForScriptExecutionsIdscriptExecutions1 = macroExecutionsForScriptExecutionsIdscriptExecutions1;
        this.parametersExecutions = parametersExecutions;
        this.scriptExecutionResults = scriptExecutionResults;
    }

    /**
     *
     * @param scriptExecutions
     */
    public ScriptExecutions(ScriptExecutions scriptExecutions) {

        this.script = scriptExecutions.getScript();
        this.stepExecutions = scriptExecutions.getStepExecutions();
        this.scriptOrder = scriptExecutions.getScriptOrder();
        this.isStimuli = scriptExecutions.getIsStimuli();
        this.macroExecutionsForScriptExecutionsIdscriptExecutions = scriptExecutions.getMacroExecutionsForScriptExecutionsIdscriptExecutions();
        this.macroExecutionsForScriptExecutionsIdscriptExecutions1 = scriptExecutions.getMacroExecutionsForScriptExecutionsIdscriptExecutions1();
        this.parametersExecutions = scriptExecutions.getParametersExecutions();
        this.scriptExecutionResults = scriptExecutions.getScriptExecutionResults();
    }

    /**
     *
     * @return
     */
    public Integer getIdscriptExecutions() {
        return this.idscriptExecutions;
    }

    /**
     *
     * @param idscriptExecutions
     */
    public void setIdscriptExecutions(Integer idscriptExecutions) {
        this.idscriptExecutions = idscriptExecutions;
    }

    /**
     *
     * @return
     */
    public Script getScript() {
        return this.script;
    }

    /**
     *
     * @param script
     */
    public void setScript(Script script) {
        this.script = script;
    }

    /**
     *
     * @return
     */
    public StepExecutions getStepExecutions() {
        return this.stepExecutions;
    }

    /**
     *
     * @param stepExecutions
     */
    public void setStepExecutions(StepExecutions stepExecutions) {
        this.stepExecutions = stepExecutions;
    }

    /**
     *
     * @return
     */
    public Byte getScriptOrder() {
        return this.scriptOrder;
    }

    /**
     *
     * @param scriptOrder
     */
    public void setScriptOrder(Byte scriptOrder) {
        this.scriptOrder = scriptOrder;
    }

    /**
     *
     * @return
     */
    public Byte getIsStimuli() {
        return this.isStimuli;
    }

    /**
     *
     * @param isStimuli
     */
    public void setIsStimuli(Byte isStimuli) {
        this.isStimuli = isStimuli;
    }

    /**
     *
     * @return
     */
    public Set getMacroExecutionsForScriptExecutionsIdscriptExecutions() {
        return this.macroExecutionsForScriptExecutionsIdscriptExecutions;
    }

    /**
     *
     * @param macroExecutionsForScriptExecutionsIdscriptExecutions
     */
    public void setMacroExecutionsForScriptExecutionsIdscriptExecutions(Set macroExecutionsForScriptExecutionsIdscriptExecutions) {
        this.macroExecutionsForScriptExecutionsIdscriptExecutions = macroExecutionsForScriptExecutionsIdscriptExecutions;
    }

    /**
     *
     * @return
     */
    public Set getMacroExecutionsForScriptExecutionsIdscriptExecutions1() {
        return this.macroExecutionsForScriptExecutionsIdscriptExecutions1;
    }

    /**
     *
     * @param macroExecutionsForScriptExecutionsIdscriptExecutions1
     */
    public void setMacroExecutionsForScriptExecutionsIdscriptExecutions1(Set macroExecutionsForScriptExecutionsIdscriptExecutions1) {
        this.macroExecutionsForScriptExecutionsIdscriptExecutions1 = macroExecutionsForScriptExecutionsIdscriptExecutions1;
    }

    /**
     *
     * @return
     */
    public Set getParametersExecutions() {
        return this.parametersExecutions;
    }

    /**
     *
     * @param parametersExecutions
     */
    public void setParametersExecutions(Set parametersExecutions) {
        this.parametersExecutions = parametersExecutions;
    }

    /**
     *
     * @return
     */
    public Set getScriptExecutionResults() {
        return this.scriptExecutionResults;
    }

    /**
     *
     * @param scriptExecutionResults
     */
    public void setScriptExecutionResults(Set scriptExecutionResults) {
        this.scriptExecutionResults = scriptExecutionResults;
    }

    /**
     *
     * @param result
     */
    public void setScriptExecutionResult(String result) {
        this.result = result;
    }

    /**
     *
     * @return
     */
    public String getScriptExecutionResult() {
        return this.result;
    }

    /**
     *
     * @param comment
     */
    public void setScriptExecutionComment(String comment) {
        this.comment = comment;
    }

    /**
     *
     * @return
     */
    public String getScriptExecutionComment() {
        return this.comment;
    }

}
