package DB;
// Generated Jun 22, 2015 4:48:57 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * TestStepHasScript generated by hbm2java
 */
public class TestStepHasScript implements java.io.Serializable,Comparable<TestStepHasScript> {

    private int idtestStepHasScript;
    private Script script;
    private TestStep testStep;
    private byte executionOrder;
    
    //@Cascade({CascadeType.MERGE})
    private Set scriptHasBeenConfigureds = new HashSet(0);

    /**
     *
     */
    public TestStepHasScript() {
    }

    /**
     *
     * @param idtestStepHasScript
     * @param script
     * @param testStep
     * @param executionOrder
     */
    public TestStepHasScript(int idtestStepHasScript, Script script, TestStep testStep, byte executionOrder) {
        this.idtestStepHasScript = idtestStepHasScript;
        this.script = script;
        this.testStep = testStep;
        this.executionOrder = executionOrder;
    }

    /**
     *
     * @param script
     * @param testStep
     * @param executionOrder
     */
    public TestStepHasScript(Script script, TestStep testStep, byte executionOrder) {
        this.script = script;
        this.testStep = testStep;
        this.executionOrder = executionOrder;
    }

    /**
     *
     * @param tshs
     */
    public TestStepHasScript(TestStepHasScript tshs) {
        this.script = tshs.getScript();
        this.testStep = tshs.getTestStep();
        this.executionOrder = tshs.getExecutionOrder();
        this.scriptHasBeenConfigureds = tshs.getScriptHasBeenConfigureds();
    }

    /**
     *
     * @param idtestStepHasScript
     * @param script
     * @param testStep
     * @param executionOrder
     * @param scriptHasBeenConfigureds
     */
    public TestStepHasScript(int idtestStepHasScript, Script script, TestStep testStep, byte executionOrder, Set scriptHasBeenConfigureds) {
        this.idtestStepHasScript = idtestStepHasScript;
        this.script = script;
        this.testStep = testStep;
        this.executionOrder = executionOrder;
        this.scriptHasBeenConfigureds = scriptHasBeenConfigureds;
    }
    
    public String toString() {
        String str = "ID: " + this.idtestStepHasScript;
        str += ", Script: " + this.script;
        str += ", TestStep: " + this.testStep;
        str += ", ExecutionOrder: " + this.executionOrder;
        str += ", scriptHasBeenConf: " + this.scriptHasBeenConfigureds;
        return str;
    }

    /**
     *
     * @return
     */
    public int getIdtestStepHasScript() {
        return this.idtestStepHasScript;
    }

    /**
     *
     * @param idtestStepHasScript
     */
    public void setIdtestStepHasScript(int idtestStepHasScript) {
        this.idtestStepHasScript = idtestStepHasScript;
    }

    /**
     *
     * @return
     */
    public Script getScript() {
        return this.script;
    }

    /**
     *
     * @param script
     */
    public void setScript(Script script) {
        this.script = script;
    }

    /**
     *
     * @return
     */
    public TestStep getTestStep() {
        return this.testStep;
    }

    /**
     *
     * @param testStep
     */
    public void setTestStep(TestStep testStep) {
        this.testStep = testStep;
    }

    /**
     *
     * @return
     */
    public byte getExecutionOrder() {
        return this.executionOrder;
    }

    /**
     *
     * @param executionOrder
     */
    public void setExecutionOrder(byte executionOrder) {
        this.executionOrder = executionOrder;
    }

    /**
     *
     * @return
     */
    public Set getScriptHasBeenConfigureds() {
        return this.scriptHasBeenConfigureds;
    }

    /**
     *
     * @param scriptHasBeenConfigureds
     */
    public void setScriptHasBeenConfigureds(Set scriptHasBeenConfigureds) {
        this.scriptHasBeenConfigureds = scriptHasBeenConfigureds;
    }

    /**
     *
     * @param scriptHasBeenConf
     */
    public void addScripthasBeenConfigured(ScriptHasBeenConfigured scriptHasBeenConf) {
        scriptHasBeenConf.setTestStepHasScript(this);
        this.scriptHasBeenConfigureds.add(scriptHasBeenConf);
    }

    @Override
    public int compareTo(TestStepHasScript o) {
        //Double.valueOf(this.cost).compareTo(Double.valueOf(o.cost));
        return Byte.valueOf(this.getExecutionOrder()).compareTo(o.getExecutionOrder());
    }

}
