package DB;
// Generated Jun 19, 2015 5:06:37 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

/**
 * TestStep generated by hbm2java
 */
public class TestStep implements java.io.Serializable, Comparable<TestStep> {

    private Integer idtestStep;
    private TestCase testCase;
    private String writer;
    private String humanStimuli;
    private String humanCheck;
    private String creationDate;
    private String editionDate;
    private Byte stepOrder;
    private Boolean blockingStep;
    private Boolean stepCondition;
    private Set stepExecutionses = new HashSet(0);
    private Set requirements = new HashSet(0);
    private Set testStepHasScripts = new HashSet(0);

    /**
     *
     */
    public TestStep() {

    }

    /**
     * @param testCase
     * @param writer
     * @param humanStimuli
     * @param humanCheck
     * @param creationDate
     * @param editionDate
     * @param stepOrder
     * @param blockingStep
     * @param stepCondition
     * @param stepExecutionses
     * @param requirements
     * @param testStepHasScripts
     */
    public TestStep(TestCase testCase, String writer, String humanStimuli, String humanCheck, String creationDate, String editionDate, Byte stepOrder, Boolean blockingStep, Boolean stepCondition, Set stepExecutionses, Set requirements, Set testStepHasScripts) {
        this.testCase = testCase;
        this.writer = writer;
        this.humanStimuli = humanStimuli;
        this.humanCheck = humanCheck;
        this.creationDate = creationDate;
        this.editionDate = editionDate;
        this.stepOrder = stepOrder;
        this.blockingStep = blockingStep;
        this.stepCondition = stepCondition;
        this.stepExecutionses = stepExecutionses;
        this.requirements = requirements;
        this.testStepHasScripts = testStepHasScripts;
    }

    /**
     * @param step
     */
    public TestStep(TestStep step) {
        this.testCase = step.getTestCase();
//        this.idtestStep = step.getIdtestStep();
        this.writer = step.getWriter();
        this.humanStimuli = step.getHumanStimuli();
        this.humanCheck = step.getHumanCheck();
        this.creationDate = step.getCreationDate();
        this.editionDate = step.getEditionDate();
        this.stepOrder = step.getStepOrder();
        this.blockingStep = step.getBlockingStep();
        this.stepCondition = step.getStepCondition();
        this.requirements = step.getRequirements();
        this.testStepHasScripts = step.getTestStepHasScripts();
    }

    /**
     * @return
     */
    public Integer getIdtestStep() {
        return this.idtestStep;
    }

    /**
     * @param idtestStep
     */
    public void setIdtestStep(Integer idtestStep) {
        this.idtestStep = idtestStep;
    }

    /**
     * @return
     */
    public TestCase getTestCase() {
        return this.testCase;
    }

    /**
     * @param testCase
     */
    public void setTestCase(TestCase testCase) {
        this.testCase = testCase;
    }

    /**
     * @return
     */
    public String getWriter() {
        return this.writer;
    }

    /**
     * @param writer
     */
    public void setWriter(String writer) {
        this.writer = writer;
    }

    /**
     * @return
     */
    public String getHumanStimuli() {
        return this.humanStimuli;
    }

    /**
     * @param humanStimuli
     */
    public void setHumanStimuli(String humanStimuli) {
        this.humanStimuli = humanStimuli;
    }

    /**
     * @return
     */
    public String getHumanCheck() {
        return this.humanCheck;
    }

    /**
     * @param humanCheck
     */
    public void setHumanCheck(String humanCheck) {
        this.humanCheck = humanCheck;
    }

    /**
     * @return
     */
    public String getCreationDate() {
        return this.creationDate;
    }

    /**
     * @param creationDate
     */
    public void setCreationDate(String creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * @return
     */
    public String getEditionDate() {
        return this.editionDate;
    }

    /**
     * @param editionDate
     */
    public void setEditionDate(String editionDate) {
        this.editionDate = editionDate;
    }

    /**
     * @return
     */
    public Byte getStepOrder() {
        return this.stepOrder;
    }

    /**
     * @param stepOrder
     */
    public void setStepOrder(Byte stepOrder) {
        this.stepOrder = stepOrder;
    }

    /**
     * @return
     */
    public Boolean getBlockingStep() {
        return this.blockingStep;
    }

    /**
     * @param blockingStep
     */
    public void setBlockingStep(Boolean blockingStep) {
        this.blockingStep = blockingStep;
    }

    /**
     * @return
     */
    public Boolean getStepCondition() {
        return this.stepCondition;
    }

    /**
     * @param stepCondition
     */
    public void setStepCondition(Boolean stepCondition) {
        this.stepCondition = stepCondition;
    }

    /**
     * @return
     */
    public Set getStepExecutionses() {
        return this.stepExecutionses;
    }

    /**
     * @param stepExecutionses
     */
    public void setStepExecutionses(Set stepExecutionses) {
        this.stepExecutionses = stepExecutionses;
    }

    /**
     * @return
     */
    public Set getRequirements() {
        return this.requirements;
    }

    /**
     * @param requirements
     */
    public void setRequirements(Set requirements) {
        this.requirements = requirements;
    }

    /**
     * @return
     */
    public Set getTestStepHasScripts() {
        return this.testStepHasScripts;
    }

    /**
     * @param testStepHasScripts
     */
    public void setTestStepHasScripts(Set<TestStepHasScript> testStepHasScripts) {
        this.testStepHasScripts = testStepHasScripts;
        Iterator<TestStepHasScript> it = testStepHasScripts.iterator();
        while (it.hasNext()) {
            it.next().setTestStep(this);
        }
    }

    /**
     * @param testStepHasScript
     */
    public void addTestStephasScript(TestStepHasScript testStepHasScript) {
        testStepHasScript.setTestStep(this);
        this.testStepHasScripts.add(testStepHasScript);
    }

    @Override
    public int compareTo(TestStep o) {
        return Integer.compare(this.getStepOrder(), o.getStepOrder());
    }

    public String toString() {
        return "ID: " + this.idtestStep;
    }

}
