package DB;
// Generated Jun 19, 2015 5:06:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TestCampaign generated by hbm2java
 */
public class TestCampaign implements java.io.Serializable {


    private Integer idtestCampaign;
    private String reference;
    private String system;
    private String writter;
    private Integer campaignVersion;
    private String description;
    private String comments;
    private String creationDate;
    private String editionDate;
    private String softwareSutRelease;
    private Integer numberTestCase;
    private Byte regressionThread;
    private String writerEmail;
    private Set users = new HashSet(0);
    private Set iterationses = new HashSet(0);
    private Set testCampaignTestCases = new HashSet(0);

    /**
     *
     */
    public TestCampaign() {
    }

    /**
     * @param reference
     * @param system
     * @param writter
     * @param campaignVersion
     * @param description
     * @param comments
     * @param creationDate
     * @param editionDate
     * @param softwareSutRelease
     * @param numberTestCase
     * @param regressionThread
     * @param writerEmail
     * @param users
     * @param iterationses
     * @param testCampaignTestCases
     */
    public TestCampaign(String reference, String system, String writter, Integer campaignVersion, String description, String comments, String creationDate, String editionDate, String softwareSutRelease, Integer numberTestCase, Byte regressionThread, String writerEmail, Set users, Set iterationses, Set testCampaignTestCases) {
        this.reference = reference;
        this.system = system;
        this.writter = writter;
        this.campaignVersion = campaignVersion;
        this.description = description;
        this.comments = comments;
        this.creationDate = creationDate;
        this.editionDate = editionDate;
        this.softwareSutRelease = softwareSutRelease;
        this.numberTestCase = numberTestCase;
        this.regressionThread = regressionThread;
        this.writerEmail = writerEmail;
        this.users = users;
        this.iterationses = iterationses;
        this.testCampaignTestCases = testCampaignTestCases;
    }

    /**
     * @return
     */
    public Integer getIdtestCampaign() {
        return this.idtestCampaign;
    }

    /**
     * @param idtestCampaign
     */
    public void setIdtestCampaign(Integer idtestCampaign) {
        this.idtestCampaign = idtestCampaign;
    }

    /**
     * @return
     */
    public String getReference() {
        return this.reference;
    }

    /**
     * @param reference
     */
    public void setReference(String reference) {
        this.reference = reference;
    }

    /**
     * @return
     */
    public String getSystem() {
        return this.system;
    }

    /**
     * @param system
     */
    public void setSystem(String system) {
        this.system = system;
    }

    /**
     * @return
     */
    public String getWritter() {
        return this.writter;
    }

    /**
     * @param writter
     */
    public void setWritter(String writter) {
        this.writter = writter;
    }

    /**
     * @return
     */
    public Integer getCampaignVersion() {
        return this.campaignVersion;
    }

    /**
     * @param campaignVersion
     */
    public void setCampaignVersion(Integer campaignVersion) {
        this.campaignVersion = campaignVersion;
    }

    /**
     * @return
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * @param description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * @return
     */
    public String getComments() {
        return this.comments;
    }

    /**
     * @param comments
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * @return
     */
    public String getCreationDate() {
        return this.creationDate;
    }

    /**
     * @param creationDate
     */
    public void setCreationDate(String creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * @return
     */
    public String getEditionDate() {
        return this.editionDate;
    }

    /**
     * @param editionDate
     */
    public void setEditionDate(String editionDate) {
        this.editionDate = editionDate;
    }

    /**
     * @return
     */
    public String getSoftwareSutRelease() {
        return this.softwareSutRelease;
    }

    /**
     * @param softwareSutRelease
     */
    public void setSoftwareSutRelease(String softwareSutRelease) {
        this.softwareSutRelease = softwareSutRelease;
    }

    /**
     * @return
     */
    public Integer getNumberTestCase() {
        return this.numberTestCase;
    }

    /**
     * @param numberTestCase
     */
    public void setNumberTestCase(Integer numberTestCase) {
        this.numberTestCase = numberTestCase;
    }

    /**
     * @return
     */
    public Byte getRegressionThread() {
        return this.regressionThread;
    }

    /**
     * @param regressionThread
     */
    public void setRegressionThread(Byte regressionThread) {
        this.regressionThread = regressionThread;
    }

    /**
     * @return
     */
    public String getWriterEmail() {
        return this.writerEmail;
    }

    /**
     * @param writerEmail
     */
    public void setWriterEmail(String writerEmail) {
        this.writerEmail = writerEmail;
    }

    /**
     * @return
     */
    public Set getUsers() {
        return this.users;
    }

    /**
     * @param users
     */
    public void setUsers(Set users) {
        this.users = users;
    }

    /**
     * @return
     */
    public Set getIterationses() {
        return this.iterationses;
    }

    /**
     * @param iterationses
     */
    public void setIterationses(Set iterationses) {
        this.iterationses = iterationses;
    }

    /**
     * @return
     */
    public Set getTestCampaignTestCases() {
        return this.testCampaignTestCases;
    }

    /**
     * @param testCampaignTestCases
     */
    public void setTestCampaignTestCases(Set testCampaignTestCases) {
        this.testCampaignTestCases = testCampaignTestCases;
    }


}


