package DB;
// Generated Jun 19, 2015 5:06:37 PM by Hibernate Tools 4.3.1


/**
 * TestCampaignTestCaseId generated by hbm2java
 */
public class TestCampaignTestCaseId implements java.io.Serializable {


    private int testCampaignIdtestCampaign;
    private int testCaseIdtestCase;
    private byte caseOrder;

    /**
     *
     */
    public TestCampaignTestCaseId() {
    }

    /**
     * @param testCampaignIdtestCampaign
     * @param testCaseIdtestCase
     * @param caseOrder
     */
    public TestCampaignTestCaseId(int testCampaignIdtestCampaign, int testCaseIdtestCase, byte caseOrder) {
        this.testCampaignIdtestCampaign = testCampaignIdtestCampaign;
        this.testCaseIdtestCase = testCaseIdtestCase;
        this.caseOrder = caseOrder;
    }

    /**
     * @return
     */
    public int getTestCampaignIdtestCampaign() {
        return this.testCampaignIdtestCampaign;
    }

    /**
     * @param testCampaignIdtestCampaign
     */
    public void setTestCampaignIdtestCampaign(int testCampaignIdtestCampaign) {
        this.testCampaignIdtestCampaign = testCampaignIdtestCampaign;
    }

    /**
     * @return
     */
    public int getTestCaseIdtestCase() {
        return this.testCaseIdtestCase;
    }

    /**
     * @param testCaseIdtestCase
     */
    public void setTestCaseIdtestCase(int testCaseIdtestCase) {
        this.testCaseIdtestCase = testCaseIdtestCase;
    }

    /**
     * @return
     */
    public byte getCaseOrder() {
        return this.caseOrder;
    }

    /**
     * @param caseOrder
     */
    public void setCaseOrder(byte caseOrder) {
        this.caseOrder = caseOrder;
    }


    public boolean equals(Object other) {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof TestCampaignTestCaseId)) return false;
        TestCampaignTestCaseId castOther = (TestCampaignTestCaseId) other;

        return (this.getTestCampaignIdtestCampaign() == castOther.getTestCampaignIdtestCampaign())
                && (this.getTestCaseIdtestCase() == castOther.getTestCaseIdtestCase())
                && (this.getCaseOrder() == castOther.getCaseOrder());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getTestCampaignIdtestCampaign();
        result = 37 * result + this.getTestCaseIdtestCase();
        result = 37 * result + this.getCaseOrder();
        return result;
    }


}


