package DB;
// Generated Jun 19, 2015 5:06:37 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TestCampaign generated by hbm2java
 */
public class TestCampaign  implements java.io.Serializable {


     private Integer idtestCampaign;
     private String reference;
     private String system;
     private String writter;
     private Integer campaignVersion;
     private String description;
     private String comments;
     private String creationDate;
     private String editionDate;
     private String softwareSutRelease;
     private Integer numberTestCase;
     private Byte regressionThread;
     private String writerEmail;
     private Set users = new HashSet(0);
     private Set iterationses = new HashSet(0);
     private Set testCampaignTestCases = new HashSet(0);

    public TestCampaign() {
    }

    public TestCampaign(String reference, String system, String writter, Integer campaignVersion, String description, String comments, String creationDate, String editionDate, String softwareSutRelease, Integer numberTestCase, Byte regressionThread, String writerEmail, Set users, Set iterationses, Set testCampaignTestCases) {
       this.reference = reference;
       this.system = system;
       this.writter = writter;
       this.campaignVersion = campaignVersion;
       this.description = description;
       this.comments = comments;
       this.creationDate = creationDate;
       this.editionDate = editionDate;
       this.softwareSutRelease = softwareSutRelease;
       this.numberTestCase = numberTestCase;
       this.regressionThread = regressionThread;
       this.writerEmail = writerEmail;
       this.users = users;
       this.iterationses = iterationses;
       this.testCampaignTestCases = testCampaignTestCases;
    }
   
    public Integer getIdtestCampaign() {
        return this.idtestCampaign;
    }
    
    public void setIdtestCampaign(Integer idtestCampaign) {
        this.idtestCampaign = idtestCampaign;
    }
    public String getReference() {
        return this.reference;
    }
    
    public void setReference(String reference) {
        this.reference = reference;
    }
    public String getSystem() {
        return this.system;
    }
    
    public void setSystem(String system) {
        this.system = system;
    }
    public String getWritter() {
        return this.writter;
    }
    
    public void setWritter(String writter) {
        this.writter = writter;
    }
    public Integer getCampaignVersion() {
        return this.campaignVersion;
    }
    
    public void setCampaignVersion(Integer campaignVersion) {
        this.campaignVersion = campaignVersion;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public String getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(String creationDate) {
        this.creationDate = creationDate;
    }
    public String getEditionDate() {
        return this.editionDate;
    }
    
    public void setEditionDate(String editionDate) {
        this.editionDate = editionDate;
    }
    public String getSoftwareSutRelease() {
        return this.softwareSutRelease;
    }
    
    public void setSoftwareSutRelease(String softwareSutRelease) {
        this.softwareSutRelease = softwareSutRelease;
    }
    public Integer getNumberTestCase() {
        return this.numberTestCase;
    }
    
    public void setNumberTestCase(Integer numberTestCase) {
        this.numberTestCase = numberTestCase;
    }
    public Byte getRegressionThread() {
        return this.regressionThread;
    }
    
    public void setRegressionThread(Byte regressionThread) {
        this.regressionThread = regressionThread;
    }
    public String getWriterEmail() {
        return this.writerEmail;
    }
    
    public void setWriterEmail(String writerEmail) {
        this.writerEmail = writerEmail;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }
    public Set getIterationses() {
        return this.iterationses;
    }
    
    public void setIterationses(Set iterationses) {
        this.iterationses = iterationses;
    }
    public Set getTestCampaignTestCases() {
        return this.testCampaignTestCases;
    }
    
    public void setTestCampaignTestCases(Set testCampaignTestCases) {
        this.testCampaignTestCases = testCampaignTestCases;
    }




}


