package DB;
// Generated Jun 19, 2015 5:06:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer idUser;
     private String login;
     private String password;
     private String right;
     private String email;
     private String name;
     private Set testCampaigns = new HashSet(0);

    public User() {
    }

    public User(String login, String password, String right, String email, String name, Set testCampaigns) {
       this.login = login;
       this.password = password;
       this.right = right;
       this.email = email;
       this.name = name;
       this.testCampaigns = testCampaigns;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getRight() {
        return this.right;
    }
    
    public void setRight(String right) {
        this.right = right;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getTestCampaigns() {
        return this.testCampaigns;
    }
    
    public void setTestCampaigns(Set testCampaigns) {
        this.testCampaigns = testCampaigns;
    }




}


