package DB;
// Generated Jun 19, 2015 5:06:37 PM by Hibernate Tools 4.3.1

import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

import java.util.HashSet;
import java.util.Set;

/**
 * TestCase generated by hbm2java
 */
public class TestCase implements java.io.Serializable {

    private Integer idtestCase;
    private String testCaseTitle;
    private String writter;
    private Byte caseInternalVersion;
    private String creationDate;
    private String editionDate;
    private String testCaseIdentification;
    private String testCaseVersion;
    private String project;
    private String typeOfTest;
    private String categoryOfTest;
    private String location;
    private String environment;
    private String testObjective;
    private Byte totalSteps;
    private String writterEmail;
    private String writingStatus;
    private String testMethodIadt;
    private Byte blocking;
    private String internalComments;
    private String testCaseSource;
    private Set testSteps = new HashSet(0);
    private Set testCampaignTestCases = new HashSet(0);
    private Set caseExecutionses = new HashSet(0);
    private SimpleStringProperty simpleStringConfigured;

    /**
     *
     */
    public TestCase() {
    }

    /**
     *Default Constructor
     * 
     * @param testCaseTitle
     * @param writter
     * @param caseInternalVersion
     * @param creationDate
     * @param editionDate
     * @param testCaseIdentification
     * @param testCaseVersion
     * @param project
     * @param typeOfTest
     * @param categoryOfTest
     * @param location
     * @param environment
     * @param testObjective
     * @param totalSteps
     * @param writterEmail
     * @param writingStatus
     * @param testMethodIadt
     * @param blocking
     * @param internalComments
     * @param testCaseSource
     * @param testSteps
     * @param testCampaignTestCases
     * @param caseExecutionses
     */
    public TestCase(String testCaseTitle, String writter, Byte caseInternalVersion, String creationDate, String editionDate, String testCaseIdentification, String testCaseVersion, String project, String typeOfTest, String categoryOfTest, String location, String environment, String testObjective, Byte totalSteps, String writterEmail, String writingStatus, String testMethodIadt, Byte blocking, String internalComments, String testCaseSource, Set testSteps, Set testCampaignTestCases, Set caseExecutionses) {
        this.testCaseTitle = testCaseTitle;
        this.writter = writter;
        this.caseInternalVersion = caseInternalVersion;
        this.creationDate = creationDate;
        this.editionDate = editionDate;
        this.testCaseIdentification = testCaseIdentification;
        this.testCaseVersion = testCaseVersion;
        this.project = project;
        this.typeOfTest = typeOfTest;
        this.categoryOfTest = categoryOfTest;
        this.location = location;
        this.environment = environment;
        this.testObjective = testObjective;
        this.totalSteps = totalSteps;
        this.writterEmail = writterEmail;
        this.writingStatus = writingStatus;
        this.testMethodIadt = testMethodIadt;
        this.blocking = blocking;
        this.internalComments = internalComments;
        this.testCaseSource = testCaseSource;
        this.testSteps = testSteps;
        this.testCampaignTestCases = testCampaignTestCases;
        this.caseExecutionses = caseExecutionses;
    }

    /**
     *
     * @param testCase
     */
    public TestCase(TestCase testCase) {
        this.testCaseTitle = testCase.getTestCaseTitle();
        this.writter = testCase.getWritter();
        this.caseInternalVersion = testCase.getCaseInternalVersion();
        this.creationDate = testCase.getCreationDate();
        this.editionDate = testCase.getEditionDate();
        this.testCaseIdentification = testCase.getTestCaseIdentification();
        this.testCaseVersion = testCase.getTestCaseVersion();
        this.project = testCase.getProject();
        this.typeOfTest = testCase.getTypeOfTest();
        this.categoryOfTest = testCase.getCategoryOfTest();
        this.location = testCase.getLocation();
        this.environment = testCase.getEnvironment();
        this.testObjective = testCase.getTestObjective();
        this.totalSteps = testCase.getTotalSteps();
        this.writterEmail = testCase.getWritterEmail();
        this.writingStatus = testCase.getWritingStatus();
        this.testMethodIadt = testCase.getTestMethodIadt();
        this.blocking = testCase.getBlocking();
        this.internalComments = testCase.getInternalComments();
        this.testCaseSource = testCase.getTestCaseSource();
        this.testSteps = testCase.getTestSteps();
        this.testCampaignTestCases = testCase.getTestCampaignTestCases();
        this.caseExecutionses = testCase.getCaseExecutionses();
    }

    /**
     *
     * @param testCaseTitle
     * @param writter
     * @param caseInternalVersion
     * @param creationDate
     * @param editionDate
     * @param testCaseIdentification
     * @param testCaseVersion
     * @param project
     * @param typeOfTest
     * @param categoryOfTest
     * @param location
     * @param environment
     * @param testObjective
     * @param totalSteps
     * @param writterEmail
     * @param writingStatus
     * @param testMethodIadt
     * @param blocking
     * @param internalComments
     * @param testCaseSource
     */
    public TestCase(String testCaseTitle, String writter, Byte caseInternalVersion, String creationDate, String editionDate, String testCaseIdentification, String testCaseVersion, String project, String typeOfTest, String categoryOfTest, String location, String environment, String testObjective, Byte totalSteps, String writterEmail, String writingStatus, String testMethodIadt, Byte blocking, String internalComments, String testCaseSource) {
        this.testCaseTitle = testCaseTitle;
        this.writter = writter;
        this.caseInternalVersion = caseInternalVersion;
        this.creationDate = creationDate;
        this.editionDate = editionDate;
        this.testCaseIdentification = testCaseIdentification;
        this.testCaseVersion = testCaseVersion;
        this.project = project;
        this.typeOfTest = typeOfTest;
        this.categoryOfTest = categoryOfTest;
        this.location = location;
        this.environment = environment;
        this.testObjective = testObjective;
        this.totalSteps = totalSteps;
        this.writterEmail = writterEmail;
        this.writingStatus = writingStatus;
        this.testMethodIadt = testMethodIadt;
        this.blocking = blocking;
        this.internalComments = internalComments;
        this.testCaseSource = testCaseSource;
    }

//    public TestCase(String testCaseTitle, String writter, Byte caseInternalVersion, Date creationDate, Date editionDate, String testCaseIdentification, String testCaseVersion, String project, String typeOfTest, String categoryOfTest, String location, String environment, String testObjective, Byte totalSteps, String writterEmail, String writingStatus, String testMethodIadt, Byte blocking, String internalComments, String testCaseSource, Set testSteps, Set testCampaignTestCases, Set caseExecutionses) {
//       this.testCaseTitle = testCaseTitle;
//       this.writter = writter;
//       this.caseInternalVersion = caseInternalVersion;
//       this.creationDate = creationDate;
//       this.editionDate = editionDate;
//       this.testCaseIdentification = testCaseIdentification;
//       this.testCaseVersion = testCaseVersion;
//       this.project = project;
//       this.typeOfTest = typeOfTest;
//       this.categoryOfTest = categoryOfTest;
//       this.location = location;
//       this.environment = environment;
//       this.testObjective = testObjective;
//       this.totalSteps = totalSteps;
//       this.writterEmail = writterEmail;
//       this.writingStatus = writingStatus;
//       this.testMethodIadt = testMethodIadt;
//       this.blocking = blocking;
//       this.internalComments = internalComments;
//       this.testCaseSource = testCaseSource;
//       this.testSteps = testSteps;
//       this.testCampaignTestCases = testCampaignTestCases;
//       this.caseExecutionses = caseExecutionses;
//    }

    /**
     *
     * @return
     */
        public Integer getIdtestCase() {
        return this.idtestCase;
    }

    /**
     *
     * @param idtestCase
     */
    public void setIdtestCase(Integer idtestCase) {
        this.idtestCase = idtestCase;
    }

    /**
     *
     * @return
     */
    public String getTestCaseTitle() {
        return this.testCaseTitle;
    }

    /**
     *
     * @param testCaseTitle
     */
    public void setTestCaseTitle(String testCaseTitle) {
        this.testCaseTitle = testCaseTitle;
    }

    /**
     *
     * @return
     */
    public String getWritter() {
        return this.writter;
    }

    /**
     *
     * @param writter
     */
    public void setWritter(String writter) {
        this.writter = writter;
    }

    /**
     *
     * @return
     */
    public Byte getCaseInternalVersion() {
        return this.caseInternalVersion;
    }

    /**
     *
     * @param caseInternalVersion
     */
    public void setCaseInternalVersion(Byte caseInternalVersion) {
        this.caseInternalVersion = caseInternalVersion;
    }

    /**
     *
     * @return
     */
    public String getCreationDate() {
        return this.creationDate;
    }

    /**
     *
     * @param creationDate
     */
    public void setCreationDate(String creationDate) {
        this.creationDate = creationDate;
    }

    /**
     *
     * @return
     */
    public String getEditionDate() {
        return this.editionDate;
    }

    /**
     *
     * @param editionDate
     */
    public void setEditionDate(String editionDate) {
        this.editionDate = editionDate;
    }

    /**
     *
     * @return
     */
    public String getTestCaseIdentification() {
        return this.testCaseIdentification;
    }

    /**
     *
     * @param testCaseIdentification
     */
    public void setTestCaseIdentification(String testCaseIdentification) {
        this.testCaseIdentification = testCaseIdentification;
    }

    /**
     *
     * @return
     */
    public String getTestCaseVersion() {
        return this.testCaseVersion;
    }

    /**
     *
     * @param testCaseVersion
     */
    public void setTestCaseVersion(String testCaseVersion) {
        this.testCaseVersion = testCaseVersion;
    }

    /**
     *
     * @return
     */
    public String getProject() {
        return this.project;
    }

    /**
     *
     * @param project
     */
    public void setProject(String project) {
        this.project = project;
    }

    /**
     *
     * @return
     */
    public String getTypeOfTest() {
        return this.typeOfTest;
    }

    /**
     *
     * @param typeOfTest
     */
    public void setTypeOfTest(String typeOfTest) {
        this.typeOfTest = typeOfTest;
    }

    /**
     *
     * @return
     */
    public String getCategoryOfTest() {
        return this.categoryOfTest;
    }

    /**
     *
     * @param categoryOfTest
     */
    public void setCategoryOfTest(String categoryOfTest) {
        this.categoryOfTest = categoryOfTest;
    }

    /**
     *
     * @return
     */
    public String getLocation() {
        return this.location;
    }

    /**
     *
     * @param location
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     *
     * @return
     */
    public String getEnvironment() {
        return this.environment;
    }

    /**
     *
     * @param environment
     */
    public void setEnvironment(String environment) {
        this.environment = environment;
    }

    /**
     *
     * @return
     */
    public String getTestObjective() {
        return this.testObjective;
    }

    /**
     *
     * @param testObjective
     */
    public void setTestObjective(String testObjective) {
        this.testObjective = testObjective;
    }

    /**
     *
     * @return
     */
    public Byte getTotalSteps() {
        return this.totalSteps;
    }

    /**
     *
     * @param totalSteps
     */
    public void setTotalSteps(Byte totalSteps) {
        this.totalSteps = totalSteps;
    }

    /**
     *
     * @return
     */
    public String getWritterEmail() {
        return this.writterEmail;
    }

    /**
     *
     * @param writterEmail
     */
    public void setWritterEmail(String writterEmail) {
        this.writterEmail = writterEmail;
    }

    /**
     *
     * @return
     */
    public String getWritingStatus() {
        return this.writingStatus;
    }

    /**
     *
     * @param writingStatus
     */
    public void setWritingStatus(String writingStatus) {
        this.writingStatus = writingStatus;
    }

    /**
     *
     * @return
     */
    public String getTestMethodIadt() {
        return this.testMethodIadt;
    }

    /**
     *
     * @param testMethodIadt
     */
    public void setTestMethodIadt(String testMethodIadt) {
        this.testMethodIadt = testMethodIadt;
    }

    /**
     *
     * @return
     */
    public Byte getBlocking() {
        return this.blocking;
    }

    /**
     *
     * @param blocking
     */
    public void setBlocking(Byte blocking) {
        this.blocking = blocking;
    }

    /**
     *
     * @return
     */
    public String getInternalComments() {
        return this.internalComments;
    }

    /**
     *
     * @param internalComments
     */
    public void setInternalComments(String internalComments) {
        this.internalComments = internalComments;
    }

    /**
     *
     * @return
     */
    public String getTestCaseSource() {
        return this.testCaseSource;
    }

    /**
     *
     * @param testCaseSource
     */
    public void setTestCaseSource(String testCaseSource) {
        this.testCaseSource = testCaseSource;
    }

    /**
     *
     * @return
     */
    public Set getTestSteps() {
        return this.testSteps;
    }

    /**
     *
     * @param testSteps
     */
    public void setTestSteps(Set testSteps) {
        this.testSteps = testSteps;
    }

    /**
     *
     * @return
     */
    public Set getTestCampaignTestCases() {
        return this.testCampaignTestCases;
    }

    /**
     *
     * @param testCampaignTestCases
     */
    public void setTestCampaignTestCases(Set testCampaignTestCases) {
        this.testCampaignTestCases = testCampaignTestCases;
    }

    /**
     *
     * @return
     */
    public Set getCaseExecutionses() {
        return this.caseExecutionses;
    }

    /**
     *
     * @param caseExecutionses
     */
    public void setCaseExecutionses(Set caseExecutionses) {
        this.caseExecutionses = caseExecutionses;
    }

    /**
     *
     * @param configured
     */
    public void setConfigured(String configured) {
        simpleStringConfiguredProperty().set(configured);
    }

    /**
     *
     * @return
     */
    public String getSimpleStringConfiguredProperty() {
        return this.simpleStringConfigured.get();
    }

    /**
     *
     * @return
     */
    public StringProperty simpleStringConfiguredProperty() {
        if (simpleStringConfigured == null) {
            simpleStringConfigured = new SimpleStringProperty(this, "NConfigured");
        }
        return simpleStringConfigured;
    }

    /**
     *
     * @param testStep
     */
    public void addStep(TestStep testStep) {
        testStep.setTestCase(this);
        this.testSteps.add(testStep);
    }
}
